namespace BlGame.FSM
{
	public enum FsmState 
	{
		FSM_STATE_FREE,
		FSM_STATE_RUN,
        FSM_STATE_SING,
		FSM_STATE_RELEASE,
        FSM_STATE_LEADING,
        FSM_STATE_LASTING,
		FSM_STATE_DEAD,
        FSM_STATE_ADMOVE,
        FSM_STATE_FORCEMOVE,
        FSM_STATE_RELIVE,
        FSM_STATE_IDLE,
	}
}