// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BSToGS.proto

#ifndef PROTOBUF_BSToGS_2eproto__INCLUDED
#define PROTOBUF_BSToGS_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace BSToGS {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BSToGS_2eproto();
void protobuf_AssignDesc_BSToGS_2eproto();
void protobuf_ShutdownFile_BSToGS_2eproto();

class AskRegister;
class OneUserLoginToken;

enum MsgID {
  eMsgToGSFromBS_Begin = 24576,
  eMsgToGSFromBS_AskRegisterRet = 24577,
  eMsgToGSFromBS_OneUserLoginToken = 24578,
  eMsgToGSFromBS_End = 25000
};
bool MsgID_IsValid(int value);
const MsgID MsgID_MIN = eMsgToGSFromBS_Begin;
const MsgID MsgID_MAX = eMsgToGSFromBS_End;
const int MsgID_ARRAYSIZE = MsgID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgID_descriptor();
inline const ::std::string& MsgID_Name(MsgID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgID_descriptor(), value);
}
inline bool MsgID_Parse(
    const ::std::string& name, MsgID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgID>(
    MsgID_descriptor(), name, value);
}
// ===================================================================

class AskRegister : public ::google::protobuf::Message {
 public:
  AskRegister();
  virtual ~AskRegister();

  AskRegister(const AskRegister& from);

  inline AskRegister& operator=(const AskRegister& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AskRegister& default_instance();

  void Swap(AskRegister* other);

  // implements Message ----------------------------------------------

  AskRegister* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AskRegister& from);
  void MergeFrom(const AskRegister& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .BSToGS.MsgID mgsid = 1 [default = eMsgToGSFromBS_AskRegisterRet];
  inline bool has_mgsid() const;
  inline void clear_mgsid();
  static const int kMgsidFieldNumber = 1;
  inline ::BSToGS::MsgID mgsid() const;
  inline void set_mgsid(::BSToGS::MsgID value);

  // optional int32 gsid = 2;
  inline bool has_gsid() const;
  inline void clear_gsid();
  static const int kGsidFieldNumber = 2;
  inline ::google::protobuf::int32 gsid() const;
  inline void set_gsid(::google::protobuf::int32 value);

  // optional int32 port = 3;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 3;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BSToGS.AskRegister)
 private:
  inline void set_has_mgsid();
  inline void clear_has_mgsid();
  inline void set_has_gsid();
  inline void clear_has_gsid();
  inline void set_has_port();
  inline void clear_has_port();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int mgsid_;
  ::google::protobuf::int32 gsid_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_BSToGS_2eproto();
  friend void protobuf_AssignDesc_BSToGS_2eproto();
  friend void protobuf_ShutdownFile_BSToGS_2eproto();

  void InitAsDefaultInstance();
  static AskRegister* default_instance_;
};
// -------------------------------------------------------------------

class OneUserLoginToken : public ::google::protobuf::Message {
 public:
  OneUserLoginToken();
  virtual ~OneUserLoginToken();

  OneUserLoginToken(const OneUserLoginToken& from);

  inline OneUserLoginToken& operator=(const OneUserLoginToken& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneUserLoginToken& default_instance();

  void Swap(OneUserLoginToken* other);

  // implements Message ----------------------------------------------

  OneUserLoginToken* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OneUserLoginToken& from);
  void MergeFrom(const OneUserLoginToken& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .BSToGS.MsgID msgid = 1 [default = eMsgToGSFromBS_OneUserLoginToken];
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgidFieldNumber = 1;
  inline ::BSToGS::MsgID msgid() const;
  inline void set_msgid(::BSToGS::MsgID value);

  // optional int32 gateclient = 2;
  inline bool has_gateclient() const;
  inline void clear_gateclient();
  static const int kGateclientFieldNumber = 2;
  inline ::google::protobuf::int32 gateclient() const;
  inline void set_gateclient(::google::protobuf::int32 value);

  // optional string token = 3;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 3;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // optional string user_name = 4;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 4;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // optional int32 port = 5;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 5;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);

  // optional string ip = 6;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIpFieldNumber = 6;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const char* value, size_t size);
  inline ::std::string* mutable_ip();
  inline ::std::string* release_ip();
  inline void set_allocated_ip(::std::string* ip);

  // @@protoc_insertion_point(class_scope:BSToGS.OneUserLoginToken)
 private:
  inline void set_has_msgid();
  inline void clear_has_msgid();
  inline void set_has_gateclient();
  inline void clear_has_gateclient();
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_ip();
  inline void clear_has_ip();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgid_;
  ::google::protobuf::int32 gateclient_;
  ::std::string* token_;
  ::std::string* user_name_;
  ::std::string* ip_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_BSToGS_2eproto();
  friend void protobuf_AssignDesc_BSToGS_2eproto();
  friend void protobuf_ShutdownFile_BSToGS_2eproto();

  void InitAsDefaultInstance();
  static OneUserLoginToken* default_instance_;
};
// ===================================================================


// ===================================================================

// AskRegister

// optional .BSToGS.MsgID mgsid = 1 [default = eMsgToGSFromBS_AskRegisterRet];
inline bool AskRegister::has_mgsid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AskRegister::set_has_mgsid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AskRegister::clear_has_mgsid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AskRegister::clear_mgsid() {
  mgsid_ = 24577;
  clear_has_mgsid();
}
inline ::BSToGS::MsgID AskRegister::mgsid() const {
  // @@protoc_insertion_point(field_get:BSToGS.AskRegister.mgsid)
  return static_cast< ::BSToGS::MsgID >(mgsid_);
}
inline void AskRegister::set_mgsid(::BSToGS::MsgID value) {
  assert(::BSToGS::MsgID_IsValid(value));
  set_has_mgsid();
  mgsid_ = value;
  // @@protoc_insertion_point(field_set:BSToGS.AskRegister.mgsid)
}

// optional int32 gsid = 2;
inline bool AskRegister::has_gsid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AskRegister::set_has_gsid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AskRegister::clear_has_gsid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AskRegister::clear_gsid() {
  gsid_ = 0;
  clear_has_gsid();
}
inline ::google::protobuf::int32 AskRegister::gsid() const {
  // @@protoc_insertion_point(field_get:BSToGS.AskRegister.gsid)
  return gsid_;
}
inline void AskRegister::set_gsid(::google::protobuf::int32 value) {
  set_has_gsid();
  gsid_ = value;
  // @@protoc_insertion_point(field_set:BSToGS.AskRegister.gsid)
}

// optional int32 port = 3;
inline bool AskRegister::has_port() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AskRegister::set_has_port() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AskRegister::clear_has_port() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AskRegister::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 AskRegister::port() const {
  // @@protoc_insertion_point(field_get:BSToGS.AskRegister.port)
  return port_;
}
inline void AskRegister::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:BSToGS.AskRegister.port)
}

// -------------------------------------------------------------------

// OneUserLoginToken

// optional .BSToGS.MsgID msgid = 1 [default = eMsgToGSFromBS_OneUserLoginToken];
inline bool OneUserLoginToken::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OneUserLoginToken::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OneUserLoginToken::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OneUserLoginToken::clear_msgid() {
  msgid_ = 24578;
  clear_has_msgid();
}
inline ::BSToGS::MsgID OneUserLoginToken::msgid() const {
  // @@protoc_insertion_point(field_get:BSToGS.OneUserLoginToken.msgid)
  return static_cast< ::BSToGS::MsgID >(msgid_);
}
inline void OneUserLoginToken::set_msgid(::BSToGS::MsgID value) {
  assert(::BSToGS::MsgID_IsValid(value));
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:BSToGS.OneUserLoginToken.msgid)
}

// optional int32 gateclient = 2;
inline bool OneUserLoginToken::has_gateclient() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OneUserLoginToken::set_has_gateclient() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OneUserLoginToken::clear_has_gateclient() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OneUserLoginToken::clear_gateclient() {
  gateclient_ = 0;
  clear_has_gateclient();
}
inline ::google::protobuf::int32 OneUserLoginToken::gateclient() const {
  // @@protoc_insertion_point(field_get:BSToGS.OneUserLoginToken.gateclient)
  return gateclient_;
}
inline void OneUserLoginToken::set_gateclient(::google::protobuf::int32 value) {
  set_has_gateclient();
  gateclient_ = value;
  // @@protoc_insertion_point(field_set:BSToGS.OneUserLoginToken.gateclient)
}

// optional string token = 3;
inline bool OneUserLoginToken::has_token() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OneUserLoginToken::set_has_token() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OneUserLoginToken::clear_has_token() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OneUserLoginToken::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& OneUserLoginToken::token() const {
  // @@protoc_insertion_point(field_get:BSToGS.OneUserLoginToken.token)
  return *token_;
}
inline void OneUserLoginToken::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:BSToGS.OneUserLoginToken.token)
}
inline void OneUserLoginToken::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:BSToGS.OneUserLoginToken.token)
}
inline void OneUserLoginToken::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BSToGS.OneUserLoginToken.token)
}
inline ::std::string* OneUserLoginToken::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:BSToGS.OneUserLoginToken.token)
  return token_;
}
inline ::std::string* OneUserLoginToken::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OneUserLoginToken::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:BSToGS.OneUserLoginToken.token)
}

// optional string user_name = 4;
inline bool OneUserLoginToken::has_user_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OneUserLoginToken::set_has_user_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OneUserLoginToken::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OneUserLoginToken::clear_user_name() {
  if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_->clear();
  }
  clear_has_user_name();
}
inline const ::std::string& OneUserLoginToken::user_name() const {
  // @@protoc_insertion_point(field_get:BSToGS.OneUserLoginToken.user_name)
  return *user_name_;
}
inline void OneUserLoginToken::set_user_name(const ::std::string& value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
  // @@protoc_insertion_point(field_set:BSToGS.OneUserLoginToken.user_name)
}
inline void OneUserLoginToken::set_user_name(const char* value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:BSToGS.OneUserLoginToken.user_name)
}
inline void OneUserLoginToken::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BSToGS.OneUserLoginToken.user_name)
}
inline ::std::string* OneUserLoginToken::mutable_user_name() {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:BSToGS.OneUserLoginToken.user_name)
  return user_name_;
}
inline ::std::string* OneUserLoginToken::release_user_name() {
  clear_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = user_name_;
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OneUserLoginToken::set_allocated_user_name(::std::string* user_name) {
  if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete user_name_;
  }
  if (user_name) {
    set_has_user_name();
    user_name_ = user_name;
  } else {
    clear_has_user_name();
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:BSToGS.OneUserLoginToken.user_name)
}

// optional int32 port = 5;
inline bool OneUserLoginToken::has_port() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OneUserLoginToken::set_has_port() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OneUserLoginToken::clear_has_port() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OneUserLoginToken::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 OneUserLoginToken::port() const {
  // @@protoc_insertion_point(field_get:BSToGS.OneUserLoginToken.port)
  return port_;
}
inline void OneUserLoginToken::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:BSToGS.OneUserLoginToken.port)
}

// optional string ip = 6;
inline bool OneUserLoginToken::has_ip() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void OneUserLoginToken::set_has_ip() {
  _has_bits_[0] |= 0x00000020u;
}
inline void OneUserLoginToken::clear_has_ip() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void OneUserLoginToken::clear_ip() {
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_->clear();
  }
  clear_has_ip();
}
inline const ::std::string& OneUserLoginToken::ip() const {
  // @@protoc_insertion_point(field_get:BSToGS.OneUserLoginToken.ip)
  return *ip_;
}
inline void OneUserLoginToken::set_ip(const ::std::string& value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
  // @@protoc_insertion_point(field_set:BSToGS.OneUserLoginToken.ip)
}
inline void OneUserLoginToken::set_ip(const char* value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
  // @@protoc_insertion_point(field_set_char:BSToGS.OneUserLoginToken.ip)
}
inline void OneUserLoginToken::set_ip(const char* value, size_t size) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BSToGS.OneUserLoginToken.ip)
}
inline ::std::string* OneUserLoginToken::mutable_ip() {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:BSToGS.OneUserLoginToken.ip)
  return ip_;
}
inline ::std::string* OneUserLoginToken::release_ip() {
  clear_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ip_;
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OneUserLoginToken::set_allocated_ip(::std::string* ip) {
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ip_;
  }
  if (ip) {
    set_has_ip();
    ip_ = ip;
  } else {
    clear_has_ip();
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:BSToGS.OneUserLoginToken.ip)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace BSToGS

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::BSToGS::MsgID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BSToGS::MsgID>() {
  return ::BSToGS::MsgID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BSToGS_2eproto__INCLUDED
