// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSToBS.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "LSToBS.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace LSToBS {

namespace {

const ::google::protobuf::Descriptor* AskRegisterRet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AskRegisterRet_reflection_ = NULL;
const ::google::protobuf::Descriptor* UserLoginToken_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserLoginToken_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MsgID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_LSToBS_2eproto() {
  protobuf_AddDesc_LSToBS_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "LSToBS.proto");
  GOOGLE_CHECK(file != NULL);
  AskRegisterRet_descriptor_ = file->message_type(0);
  static const int AskRegisterRet_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AskRegisterRet, msgid_),
  };
  AskRegisterRet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AskRegisterRet_descriptor_,
      AskRegisterRet::default_instance_,
      AskRegisterRet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AskRegisterRet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AskRegisterRet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AskRegisterRet));
  UserLoginToken_descriptor_ = file->message_type(1);
  static const int UserLoginToken_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLoginToken, msgid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLoginToken, uin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLoginToken, sessionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLoginToken, platform_),
  };
  UserLoginToken_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UserLoginToken_descriptor_,
      UserLoginToken::default_instance_,
      UserLoginToken_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLoginToken, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLoginToken, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UserLoginToken));
  MsgID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_LSToBS_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AskRegisterRet_descriptor_, &AskRegisterRet::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UserLoginToken_descriptor_, &UserLoginToken::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_LSToBS_2eproto() {
  delete AskRegisterRet::default_instance_;
  delete AskRegisterRet_reflection_;
  delete UserLoginToken::default_instance_;
  delete UserLoginToken_reflection_;
}

void protobuf_AddDesc_LSToBS_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014LSToBS.proto\022\006LSToBS\"M\n\016AskRegisterRet"
    "\022;\n\005msgid\030\001 \001(\0162\r.LSToBS.MsgID:\035eMsgToBS"
    "FromLS_AskRegisterRet\"\207\001\n\016UserLoginToken"
    "\022C\n\005msgid\030\001 \001(\0162\r.LSToBS.MsgID:%eMsgToBS"
    "FromLS_OneClinetLoginCheckRet\022\013\n\003uin\030\002 \001"
    "(\t\022\021\n\tsessionid\030\003 \001(\t\022\020\n\010platform\030\004 \001(\r*"
    "\217\001\n\005MsgID\022\032\n\024eMsgToBSFromLS_Begin\020\200\200\002\022#\n"
    "\035eMsgToBSFromLS_AskRegisterRet\020\201\200\002\022+\n%eM"
    "sgToBSFromLS_OneClinetLoginCheckRet\020\202\200\002\022"
    "\030\n\022eMsgToBSFromLS_End\020\240\200\002", 385);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "LSToBS.proto", &protobuf_RegisterTypes);
  AskRegisterRet::default_instance_ = new AskRegisterRet();
  UserLoginToken::default_instance_ = new UserLoginToken();
  AskRegisterRet::default_instance_->InitAsDefaultInstance();
  UserLoginToken::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_LSToBS_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_LSToBS_2eproto {
  StaticDescriptorInitializer_LSToBS_2eproto() {
    protobuf_AddDesc_LSToBS_2eproto();
  }
} static_descriptor_initializer_LSToBS_2eproto_;
const ::google::protobuf::EnumDescriptor* MsgID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgID_descriptor_;
}
bool MsgID_IsValid(int value) {
  switch(value) {
    case 32768:
    case 32769:
    case 32770:
    case 32800:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int AskRegisterRet::kMsgidFieldNumber;
#endif  // !_MSC_VER

AskRegisterRet::AskRegisterRet()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:LSToBS.AskRegisterRet)
}

void AskRegisterRet::InitAsDefaultInstance() {
}

AskRegisterRet::AskRegisterRet(const AskRegisterRet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:LSToBS.AskRegisterRet)
}

void AskRegisterRet::SharedCtor() {
  _cached_size_ = 0;
  msgid_ = 32769;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AskRegisterRet::~AskRegisterRet() {
  // @@protoc_insertion_point(destructor:LSToBS.AskRegisterRet)
  SharedDtor();
}

void AskRegisterRet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AskRegisterRet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AskRegisterRet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AskRegisterRet_descriptor_;
}

const AskRegisterRet& AskRegisterRet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_LSToBS_2eproto();
  return *default_instance_;
}

AskRegisterRet* AskRegisterRet::default_instance_ = NULL;

AskRegisterRet* AskRegisterRet::New() const {
  return new AskRegisterRet;
}

void AskRegisterRet::Clear() {
  msgid_ = 32769;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AskRegisterRet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LSToBS.AskRegisterRet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_AskRegisterRet];
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::LSToBS::MsgID_IsValid(value)) {
            set_msgid(static_cast< ::LSToBS::MsgID >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LSToBS.AskRegisterRet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LSToBS.AskRegisterRet)
  return false;
#undef DO_
}

void AskRegisterRet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LSToBS.AskRegisterRet)
  // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_AskRegisterRet];
  if (has_msgid()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:LSToBS.AskRegisterRet)
}

::google::protobuf::uint8* AskRegisterRet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:LSToBS.AskRegisterRet)
  // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_AskRegisterRet];
  if (has_msgid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LSToBS.AskRegisterRet)
  return target;
}

int AskRegisterRet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_AskRegisterRet];
    if (has_msgid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AskRegisterRet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AskRegisterRet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AskRegisterRet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AskRegisterRet::MergeFrom(const AskRegisterRet& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgid()) {
      set_msgid(from.msgid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AskRegisterRet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AskRegisterRet::CopyFrom(const AskRegisterRet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AskRegisterRet::IsInitialized() const {

  return true;
}

void AskRegisterRet::Swap(AskRegisterRet* other) {
  if (other != this) {
    std::swap(msgid_, other->msgid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AskRegisterRet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AskRegisterRet_descriptor_;
  metadata.reflection = AskRegisterRet_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int UserLoginToken::kMsgidFieldNumber;
const int UserLoginToken::kUinFieldNumber;
const int UserLoginToken::kSessionidFieldNumber;
const int UserLoginToken::kPlatformFieldNumber;
#endif  // !_MSC_VER

UserLoginToken::UserLoginToken()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:LSToBS.UserLoginToken)
}

void UserLoginToken::InitAsDefaultInstance() {
}

UserLoginToken::UserLoginToken(const UserLoginToken& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:LSToBS.UserLoginToken)
}

void UserLoginToken::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  msgid_ = 32770;
  uin_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  platform_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UserLoginToken::~UserLoginToken() {
  // @@protoc_insertion_point(destructor:LSToBS.UserLoginToken)
  SharedDtor();
}

void UserLoginToken::SharedDtor() {
  if (uin_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uin_;
  }
  if (sessionid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sessionid_;
  }
  if (this != default_instance_) {
  }
}

void UserLoginToken::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserLoginToken::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserLoginToken_descriptor_;
}

const UserLoginToken& UserLoginToken::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_LSToBS_2eproto();
  return *default_instance_;
}

UserLoginToken* UserLoginToken::default_instance_ = NULL;

UserLoginToken* UserLoginToken::New() const {
  return new UserLoginToken;
}

void UserLoginToken::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    msgid_ = 32770;
    if (has_uin()) {
      if (uin_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        uin_->clear();
      }
    }
    if (has_sessionid()) {
      if (sessionid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        sessionid_->clear();
      }
    }
    platform_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UserLoginToken::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LSToBS.UserLoginToken)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_OneClinetLoginCheckRet];
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::LSToBS::MsgID_IsValid(value)) {
            set_msgid(static_cast< ::LSToBS::MsgID >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_uin;
        break;
      }

      // optional string uin = 2;
      case 2: {
        if (tag == 18) {
         parse_uin:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uin()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->uin().data(), this->uin().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "uin");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_sessionid;
        break;
      }

      // optional string sessionid = 3;
      case 3: {
        if (tag == 26) {
         parse_sessionid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sessionid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->sessionid().data(), this->sessionid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sessionid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_platform;
        break;
      }

      // optional uint32 platform = 4;
      case 4: {
        if (tag == 32) {
         parse_platform:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &platform_)));
          set_has_platform();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LSToBS.UserLoginToken)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LSToBS.UserLoginToken)
  return false;
#undef DO_
}

void UserLoginToken::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LSToBS.UserLoginToken)
  // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_OneClinetLoginCheckRet];
  if (has_msgid()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgid(), output);
  }

  // optional string uin = 2;
  if (has_uin()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uin().data(), this->uin().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uin");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->uin(), output);
  }

  // optional string sessionid = 3;
  if (has_sessionid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sessionid().data(), this->sessionid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sessionid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sessionid(), output);
  }

  // optional uint32 platform = 4;
  if (has_platform()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->platform(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:LSToBS.UserLoginToken)
}

::google::protobuf::uint8* UserLoginToken::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:LSToBS.UserLoginToken)
  // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_OneClinetLoginCheckRet];
  if (has_msgid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgid(), target);
  }

  // optional string uin = 2;
  if (has_uin()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uin().data(), this->uin().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uin");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->uin(), target);
  }

  // optional string sessionid = 3;
  if (has_sessionid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sessionid().data(), this->sessionid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sessionid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sessionid(), target);
  }

  // optional uint32 platform = 4;
  if (has_platform()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->platform(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LSToBS.UserLoginToken)
  return target;
}

int UserLoginToken::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .LSToBS.MsgID msgid = 1 [default = eMsgToBSFromLS_OneClinetLoginCheckRet];
    if (has_msgid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgid());
    }

    // optional string uin = 2;
    if (has_uin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uin());
    }

    // optional string sessionid = 3;
    if (has_sessionid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sessionid());
    }

    // optional uint32 platform = 4;
    if (has_platform()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->platform());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UserLoginToken::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UserLoginToken* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UserLoginToken*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UserLoginToken::MergeFrom(const UserLoginToken& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgid()) {
      set_msgid(from.msgid());
    }
    if (from.has_uin()) {
      set_uin(from.uin());
    }
    if (from.has_sessionid()) {
      set_sessionid(from.sessionid());
    }
    if (from.has_platform()) {
      set_platform(from.platform());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UserLoginToken::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserLoginToken::CopyFrom(const UserLoginToken& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserLoginToken::IsInitialized() const {

  return true;
}

void UserLoginToken::Swap(UserLoginToken* other) {
  if (other != this) {
    std::swap(msgid_, other->msgid_);
    std::swap(uin_, other->uin_);
    std::swap(sessionid_, other->sessionid_);
    std::swap(platform_, other->platform_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UserLoginToken::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserLoginToken_descriptor_;
  metadata.reflection = UserLoginToken_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace LSToBS

// @@protoc_insertion_point(global_scope)
