// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SSToGS.proto

#ifndef PROTOBUF_SSToGS_2eproto__INCLUDED
#define PROTOBUF_SSToGS_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace SSToGS {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_SSToGS_2eproto();
void protobuf_AssignDesc_SSToGS_2eproto();
void protobuf_ShutdownFile_SSToGS_2eproto();

class AskPingRet;
class AskRegisteRet;
class OrderPostToGC;
class OrderPostToGC_UserNetInfo;
class OrderKickoutGC;

enum MsgID {
  eMsgToGSFromSS_Begin = 24576,
  eMsgToGSFromSS_AskPingRet = 24577,
  eMsgToGSFromSS_AskRegisteRet = 24578,
  eMsgToGSFromSS_OrderPostToGC = 24579,
  eMsgToGSFromSS_OrderKickoutGC = 24580,
  eMsgToGSFromSS_End = 25000
};
bool MsgID_IsValid(int value);
const MsgID MsgID_MIN = eMsgToGSFromSS_Begin;
const MsgID MsgID_MAX = eMsgToGSFromSS_End;
const int MsgID_ARRAYSIZE = MsgID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgID_descriptor();
inline const ::std::string& MsgID_Name(MsgID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgID_descriptor(), value);
}
inline bool MsgID_Parse(
    const ::std::string& name, MsgID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgID>(
    MsgID_descriptor(), name, value);
}
// ===================================================================

class AskPingRet : public ::google::protobuf::Message {
 public:
  AskPingRet();
  virtual ~AskPingRet();

  AskPingRet(const AskPingRet& from);

  inline AskPingRet& operator=(const AskPingRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AskPingRet& default_instance();

  void Swap(AskPingRet* other);

  // implements Message ----------------------------------------------

  AskPingRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AskPingRet& from);
  void MergeFrom(const AskPingRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .SSToGS.MsgID mgsid = 1 [default = eMsgToGSFromSS_AskPingRet];
  inline bool has_mgsid() const;
  inline void clear_mgsid();
  static const int kMgsidFieldNumber = 1;
  inline ::SSToGS::MsgID mgsid() const;
  inline void set_mgsid(::SSToGS::MsgID value);

  // optional int64 time = 2;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline ::google::protobuf::int64 time() const;
  inline void set_time(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:SSToGS.AskPingRet)
 private:
  inline void set_has_mgsid();
  inline void clear_has_mgsid();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 time_;
  int mgsid_;
  friend void  protobuf_AddDesc_SSToGS_2eproto();
  friend void protobuf_AssignDesc_SSToGS_2eproto();
  friend void protobuf_ShutdownFile_SSToGS_2eproto();

  void InitAsDefaultInstance();
  static AskPingRet* default_instance_;
};
// -------------------------------------------------------------------

class AskRegisteRet : public ::google::protobuf::Message {
 public:
  AskRegisteRet();
  virtual ~AskRegisteRet();

  AskRegisteRet(const AskRegisteRet& from);

  inline AskRegisteRet& operator=(const AskRegisteRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AskRegisteRet& default_instance();

  void Swap(AskRegisteRet* other);

  // implements Message ----------------------------------------------

  AskRegisteRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AskRegisteRet& from);
  void MergeFrom(const AskRegisteRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .SSToGS.MsgID mgsid = 1 [default = eMsgToGSFromSS_AskRegisteRet];
  inline bool has_mgsid() const;
  inline void clear_mgsid();
  static const int kMgsidFieldNumber = 1;
  inline ::SSToGS::MsgID mgsid() const;
  inline void set_mgsid(::SSToGS::MsgID value);

  // optional int32 state = 2;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 2;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SSToGS.AskRegisteRet)
 private:
  inline void set_has_mgsid();
  inline void clear_has_mgsid();
  inline void set_has_state();
  inline void clear_has_state();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int mgsid_;
  ::google::protobuf::int32 state_;
  friend void  protobuf_AddDesc_SSToGS_2eproto();
  friend void protobuf_AssignDesc_SSToGS_2eproto();
  friend void protobuf_ShutdownFile_SSToGS_2eproto();

  void InitAsDefaultInstance();
  static AskRegisteRet* default_instance_;
};
// -------------------------------------------------------------------

class OrderPostToGC_UserNetInfo : public ::google::protobuf::Message {
 public:
  OrderPostToGC_UserNetInfo();
  virtual ~OrderPostToGC_UserNetInfo();

  OrderPostToGC_UserNetInfo(const OrderPostToGC_UserNetInfo& from);

  inline OrderPostToGC_UserNetInfo& operator=(const OrderPostToGC_UserNetInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrderPostToGC_UserNetInfo& default_instance();

  void Swap(OrderPostToGC_UserNetInfo* other);

  // implements Message ----------------------------------------------

  OrderPostToGC_UserNetInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrderPostToGC_UserNetInfo& from);
  void MergeFrom(const OrderPostToGC_UserNetInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 gsid = 1;
  inline bool has_gsid() const;
  inline void clear_gsid();
  static const int kGsidFieldNumber = 1;
  inline ::google::protobuf::int32 gsid() const;
  inline void set_gsid(::google::protobuf::int32 value);

  // optional int32 gcnid = 2;
  inline bool has_gcnid() const;
  inline void clear_gcnid();
  static const int kGcnidFieldNumber = 2;
  inline ::google::protobuf::int32 gcnid() const;
  inline void set_gcnid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SSToGS.OrderPostToGC.UserNetInfo)
 private:
  inline void set_has_gsid();
  inline void clear_has_gsid();
  inline void set_has_gcnid();
  inline void clear_has_gcnid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 gsid_;
  ::google::protobuf::int32 gcnid_;
  friend void  protobuf_AddDesc_SSToGS_2eproto();
  friend void protobuf_AssignDesc_SSToGS_2eproto();
  friend void protobuf_ShutdownFile_SSToGS_2eproto();

  void InitAsDefaultInstance();
  static OrderPostToGC_UserNetInfo* default_instance_;
};
// -------------------------------------------------------------------

class OrderPostToGC : public ::google::protobuf::Message {
 public:
  OrderPostToGC();
  virtual ~OrderPostToGC();

  OrderPostToGC(const OrderPostToGC& from);

  inline OrderPostToGC& operator=(const OrderPostToGC& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrderPostToGC& default_instance();

  void Swap(OrderPostToGC* other);

  // implements Message ----------------------------------------------

  OrderPostToGC* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrderPostToGC& from);
  void MergeFrom(const OrderPostToGC& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef OrderPostToGC_UserNetInfo UserNetInfo;

  // accessors -------------------------------------------------------

  // optional .SSToGS.MsgID msgid = 1 [default = eMsgToGSFromSS_OrderPostToGC];
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgidFieldNumber = 1;
  inline ::SSToGS::MsgID msgid() const;
  inline void set_msgid(::SSToGS::MsgID value);

  // repeated .SSToGS.OrderPostToGC.UserNetInfo usernetinfo = 2;
  inline int usernetinfo_size() const;
  inline void clear_usernetinfo();
  static const int kUsernetinfoFieldNumber = 2;
  inline const ::SSToGS::OrderPostToGC_UserNetInfo& usernetinfo(int index) const;
  inline ::SSToGS::OrderPostToGC_UserNetInfo* mutable_usernetinfo(int index);
  inline ::SSToGS::OrderPostToGC_UserNetInfo* add_usernetinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::SSToGS::OrderPostToGC_UserNetInfo >&
      usernetinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::SSToGS::OrderPostToGC_UserNetInfo >*
      mutable_usernetinfo();

  // optional int32 othermsgid = 3;
  inline bool has_othermsgid() const;
  inline void clear_othermsgid();
  static const int kOthermsgidFieldNumber = 3;
  inline ::google::protobuf::int32 othermsgid() const;
  inline void set_othermsgid(::google::protobuf::int32 value);

  // optional string othermsg = 4;
  inline bool has_othermsg() const;
  inline void clear_othermsg();
  static const int kOthermsgFieldNumber = 4;
  inline const ::std::string& othermsg() const;
  inline void set_othermsg(const ::std::string& value);
  inline void set_othermsg(const char* value);
  inline void set_othermsg(const char* value, size_t size);
  inline ::std::string* mutable_othermsg();
  inline ::std::string* release_othermsg();
  inline void set_allocated_othermsg(::std::string* othermsg);

  // @@protoc_insertion_point(class_scope:SSToGS.OrderPostToGC)
 private:
  inline void set_has_msgid();
  inline void clear_has_msgid();
  inline void set_has_othermsgid();
  inline void clear_has_othermsgid();
  inline void set_has_othermsg();
  inline void clear_has_othermsg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::SSToGS::OrderPostToGC_UserNetInfo > usernetinfo_;
  int msgid_;
  ::google::protobuf::int32 othermsgid_;
  ::std::string* othermsg_;
  friend void  protobuf_AddDesc_SSToGS_2eproto();
  friend void protobuf_AssignDesc_SSToGS_2eproto();
  friend void protobuf_ShutdownFile_SSToGS_2eproto();

  void InitAsDefaultInstance();
  static OrderPostToGC* default_instance_;
};
// -------------------------------------------------------------------

class OrderKickoutGC : public ::google::protobuf::Message {
 public:
  OrderKickoutGC();
  virtual ~OrderKickoutGC();

  OrderKickoutGC(const OrderKickoutGC& from);

  inline OrderKickoutGC& operator=(const OrderKickoutGC& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrderKickoutGC& default_instance();

  void Swap(OrderKickoutGC* other);

  // implements Message ----------------------------------------------

  OrderKickoutGC* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrderKickoutGC& from);
  void MergeFrom(const OrderKickoutGC& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .SSToGS.MsgID mgsid = 1 [default = eMsgToGSFromSS_OrderKickoutGC];
  inline bool has_mgsid() const;
  inline void clear_mgsid();
  static const int kMgsidFieldNumber = 1;
  inline ::SSToGS::MsgID mgsid() const;
  inline void set_mgsid(::SSToGS::MsgID value);

  // optional int32 gsnid = 2;
  inline bool has_gsnid() const;
  inline void clear_gsnid();
  static const int kGsnidFieldNumber = 2;
  inline ::google::protobuf::int32 gsnid() const;
  inline void set_gsnid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SSToGS.OrderKickoutGC)
 private:
  inline void set_has_mgsid();
  inline void clear_has_mgsid();
  inline void set_has_gsnid();
  inline void clear_has_gsnid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int mgsid_;
  ::google::protobuf::int32 gsnid_;
  friend void  protobuf_AddDesc_SSToGS_2eproto();
  friend void protobuf_AssignDesc_SSToGS_2eproto();
  friend void protobuf_ShutdownFile_SSToGS_2eproto();

  void InitAsDefaultInstance();
  static OrderKickoutGC* default_instance_;
};
// ===================================================================


// ===================================================================

// AskPingRet

// optional .SSToGS.MsgID mgsid = 1 [default = eMsgToGSFromSS_AskPingRet];
inline bool AskPingRet::has_mgsid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AskPingRet::set_has_mgsid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AskPingRet::clear_has_mgsid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AskPingRet::clear_mgsid() {
  mgsid_ = 24577;
  clear_has_mgsid();
}
inline ::SSToGS::MsgID AskPingRet::mgsid() const {
  // @@protoc_insertion_point(field_get:SSToGS.AskPingRet.mgsid)
  return static_cast< ::SSToGS::MsgID >(mgsid_);
}
inline void AskPingRet::set_mgsid(::SSToGS::MsgID value) {
  assert(::SSToGS::MsgID_IsValid(value));
  set_has_mgsid();
  mgsid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.AskPingRet.mgsid)
}

// optional int64 time = 2;
inline bool AskPingRet::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AskPingRet::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AskPingRet::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AskPingRet::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::int64 AskPingRet::time() const {
  // @@protoc_insertion_point(field_get:SSToGS.AskPingRet.time)
  return time_;
}
inline void AskPingRet::set_time(::google::protobuf::int64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.AskPingRet.time)
}

// -------------------------------------------------------------------

// AskRegisteRet

// optional .SSToGS.MsgID mgsid = 1 [default = eMsgToGSFromSS_AskRegisteRet];
inline bool AskRegisteRet::has_mgsid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AskRegisteRet::set_has_mgsid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AskRegisteRet::clear_has_mgsid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AskRegisteRet::clear_mgsid() {
  mgsid_ = 24578;
  clear_has_mgsid();
}
inline ::SSToGS::MsgID AskRegisteRet::mgsid() const {
  // @@protoc_insertion_point(field_get:SSToGS.AskRegisteRet.mgsid)
  return static_cast< ::SSToGS::MsgID >(mgsid_);
}
inline void AskRegisteRet::set_mgsid(::SSToGS::MsgID value) {
  assert(::SSToGS::MsgID_IsValid(value));
  set_has_mgsid();
  mgsid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.AskRegisteRet.mgsid)
}

// optional int32 state = 2;
inline bool AskRegisteRet::has_state() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AskRegisteRet::set_has_state() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AskRegisteRet::clear_has_state() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AskRegisteRet::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 AskRegisteRet::state() const {
  // @@protoc_insertion_point(field_get:SSToGS.AskRegisteRet.state)
  return state_;
}
inline void AskRegisteRet::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.AskRegisteRet.state)
}

// -------------------------------------------------------------------

// OrderPostToGC_UserNetInfo

// optional int32 gsid = 1;
inline bool OrderPostToGC_UserNetInfo::has_gsid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrderPostToGC_UserNetInfo::set_has_gsid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrderPostToGC_UserNetInfo::clear_has_gsid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrderPostToGC_UserNetInfo::clear_gsid() {
  gsid_ = 0;
  clear_has_gsid();
}
inline ::google::protobuf::int32 OrderPostToGC_UserNetInfo::gsid() const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderPostToGC.UserNetInfo.gsid)
  return gsid_;
}
inline void OrderPostToGC_UserNetInfo::set_gsid(::google::protobuf::int32 value) {
  set_has_gsid();
  gsid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.OrderPostToGC.UserNetInfo.gsid)
}

// optional int32 gcnid = 2;
inline bool OrderPostToGC_UserNetInfo::has_gcnid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrderPostToGC_UserNetInfo::set_has_gcnid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrderPostToGC_UserNetInfo::clear_has_gcnid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrderPostToGC_UserNetInfo::clear_gcnid() {
  gcnid_ = 0;
  clear_has_gcnid();
}
inline ::google::protobuf::int32 OrderPostToGC_UserNetInfo::gcnid() const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderPostToGC.UserNetInfo.gcnid)
  return gcnid_;
}
inline void OrderPostToGC_UserNetInfo::set_gcnid(::google::protobuf::int32 value) {
  set_has_gcnid();
  gcnid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.OrderPostToGC.UserNetInfo.gcnid)
}

// -------------------------------------------------------------------

// OrderPostToGC

// optional .SSToGS.MsgID msgid = 1 [default = eMsgToGSFromSS_OrderPostToGC];
inline bool OrderPostToGC::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrderPostToGC::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrderPostToGC::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrderPostToGC::clear_msgid() {
  msgid_ = 24579;
  clear_has_msgid();
}
inline ::SSToGS::MsgID OrderPostToGC::msgid() const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderPostToGC.msgid)
  return static_cast< ::SSToGS::MsgID >(msgid_);
}
inline void OrderPostToGC::set_msgid(::SSToGS::MsgID value) {
  assert(::SSToGS::MsgID_IsValid(value));
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.OrderPostToGC.msgid)
}

// repeated .SSToGS.OrderPostToGC.UserNetInfo usernetinfo = 2;
inline int OrderPostToGC::usernetinfo_size() const {
  return usernetinfo_.size();
}
inline void OrderPostToGC::clear_usernetinfo() {
  usernetinfo_.Clear();
}
inline const ::SSToGS::OrderPostToGC_UserNetInfo& OrderPostToGC::usernetinfo(int index) const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderPostToGC.usernetinfo)
  return usernetinfo_.Get(index);
}
inline ::SSToGS::OrderPostToGC_UserNetInfo* OrderPostToGC::mutable_usernetinfo(int index) {
  // @@protoc_insertion_point(field_mutable:SSToGS.OrderPostToGC.usernetinfo)
  return usernetinfo_.Mutable(index);
}
inline ::SSToGS::OrderPostToGC_UserNetInfo* OrderPostToGC::add_usernetinfo() {
  // @@protoc_insertion_point(field_add:SSToGS.OrderPostToGC.usernetinfo)
  return usernetinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SSToGS::OrderPostToGC_UserNetInfo >&
OrderPostToGC::usernetinfo() const {
  // @@protoc_insertion_point(field_list:SSToGS.OrderPostToGC.usernetinfo)
  return usernetinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::SSToGS::OrderPostToGC_UserNetInfo >*
OrderPostToGC::mutable_usernetinfo() {
  // @@protoc_insertion_point(field_mutable_list:SSToGS.OrderPostToGC.usernetinfo)
  return &usernetinfo_;
}

// optional int32 othermsgid = 3;
inline bool OrderPostToGC::has_othermsgid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OrderPostToGC::set_has_othermsgid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OrderPostToGC::clear_has_othermsgid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OrderPostToGC::clear_othermsgid() {
  othermsgid_ = 0;
  clear_has_othermsgid();
}
inline ::google::protobuf::int32 OrderPostToGC::othermsgid() const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderPostToGC.othermsgid)
  return othermsgid_;
}
inline void OrderPostToGC::set_othermsgid(::google::protobuf::int32 value) {
  set_has_othermsgid();
  othermsgid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.OrderPostToGC.othermsgid)
}

// optional string othermsg = 4;
inline bool OrderPostToGC::has_othermsg() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OrderPostToGC::set_has_othermsg() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OrderPostToGC::clear_has_othermsg() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OrderPostToGC::clear_othermsg() {
  if (othermsg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    othermsg_->clear();
  }
  clear_has_othermsg();
}
inline const ::std::string& OrderPostToGC::othermsg() const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderPostToGC.othermsg)
  return *othermsg_;
}
inline void OrderPostToGC::set_othermsg(const ::std::string& value) {
  set_has_othermsg();
  if (othermsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    othermsg_ = new ::std::string;
  }
  othermsg_->assign(value);
  // @@protoc_insertion_point(field_set:SSToGS.OrderPostToGC.othermsg)
}
inline void OrderPostToGC::set_othermsg(const char* value) {
  set_has_othermsg();
  if (othermsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    othermsg_ = new ::std::string;
  }
  othermsg_->assign(value);
  // @@protoc_insertion_point(field_set_char:SSToGS.OrderPostToGC.othermsg)
}
inline void OrderPostToGC::set_othermsg(const char* value, size_t size) {
  set_has_othermsg();
  if (othermsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    othermsg_ = new ::std::string;
  }
  othermsg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SSToGS.OrderPostToGC.othermsg)
}
inline ::std::string* OrderPostToGC::mutable_othermsg() {
  set_has_othermsg();
  if (othermsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    othermsg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SSToGS.OrderPostToGC.othermsg)
  return othermsg_;
}
inline ::std::string* OrderPostToGC::release_othermsg() {
  clear_has_othermsg();
  if (othermsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = othermsg_;
    othermsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrderPostToGC::set_allocated_othermsg(::std::string* othermsg) {
  if (othermsg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete othermsg_;
  }
  if (othermsg) {
    set_has_othermsg();
    othermsg_ = othermsg;
  } else {
    clear_has_othermsg();
    othermsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SSToGS.OrderPostToGC.othermsg)
}

// -------------------------------------------------------------------

// OrderKickoutGC

// optional .SSToGS.MsgID mgsid = 1 [default = eMsgToGSFromSS_OrderKickoutGC];
inline bool OrderKickoutGC::has_mgsid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrderKickoutGC::set_has_mgsid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrderKickoutGC::clear_has_mgsid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrderKickoutGC::clear_mgsid() {
  mgsid_ = 24580;
  clear_has_mgsid();
}
inline ::SSToGS::MsgID OrderKickoutGC::mgsid() const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderKickoutGC.mgsid)
  return static_cast< ::SSToGS::MsgID >(mgsid_);
}
inline void OrderKickoutGC::set_mgsid(::SSToGS::MsgID value) {
  assert(::SSToGS::MsgID_IsValid(value));
  set_has_mgsid();
  mgsid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.OrderKickoutGC.mgsid)
}

// optional int32 gsnid = 2;
inline bool OrderKickoutGC::has_gsnid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrderKickoutGC::set_has_gsnid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrderKickoutGC::clear_has_gsnid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrderKickoutGC::clear_gsnid() {
  gsnid_ = 0;
  clear_has_gsnid();
}
inline ::google::protobuf::int32 OrderKickoutGC::gsnid() const {
  // @@protoc_insertion_point(field_get:SSToGS.OrderKickoutGC.gsnid)
  return gsnid_;
}
inline void OrderKickoutGC::set_gsnid(::google::protobuf::int32 value) {
  set_has_gsnid();
  gsnid_ = value;
  // @@protoc_insertion_point(field_set:SSToGS.OrderKickoutGC.gsnid)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SSToGS

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::SSToGS::MsgID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SSToGS::MsgID>() {
  return ::SSToGS::MsgID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SSToGS_2eproto__INCLUDED
